name: vcon
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip:
    - -r requirements.txt
  - requests
  - cryptography
  - authlib
  - pydash
  - uuid6
  - pytest
  - packaging
  - pluggy
  - pycparser
  - iniconfig